import { useEffect,useMemo,useState } from "react";
import { AppBar,Box,Checkbox,Chip,Container,FormControl,FormControlLabel,IconButton,InputLabel,MenuItem,Paper,Select,Stack,Tab,Tabs,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Toolbar,Typography } from "@mui/material";
import { Home as HomeIcon } from "@mui/icons-material";
import { CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { useNavigate,useSearchParams } from "react-router-dom";

type Row=Record<string,string|number|null|undefined>;
type Payload={metadata:{coverage:{from:string;to:string}};forecastColumns:string[];opinionColumns:string[];forecasts:unknown[][];opinions:unknown[][]};
const colors=["#f28c28","#4da3ff","#33c37d","#c084fc","#ef6b6b","#f2c94c","#67e8f9","#fb7185"];
const labels:Record<string,string>={INF_GEN:"Inflación general",INF_SUB:"Inflación subyacente",GDP_REAL:"Crecimiento del PIB",FONDEO:"Tasa de fondeo",CETE28:"Cetes a 28 días",OTHER:"Bono M a 10 años",OP_ENV:"Percepción del entorno",OP_FACTORS:"Factores que obstaculizan el crecimiento",OP_COMP:"Condiciones de competencia"};
const statLabels:Record<string,string>={median:"Mediana",mean:"Media",q1:"Q1",q3:"Q3",max:"Máximo",min:"Mínimo"};
const groups={rates:{label:"Tasas",indicators:["FONDEO","CETE28","OTHER"]},inflation:{label:"Inflación",indicators:["INF_GEN","INF_SUB"]},gdp:{label:"PIB",indicators:["GDP_REAL"]}} as const;
const fmt=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v.toFixed(2):"—";
const objects=(cols:string[],rows:unknown[][])=>rows.map(row=>Object.fromEntries(cols.map((c,i)=>[c,row[i]])) as Row);

export default function ExpectationsRadar(){
 const [data,setData]=useState<Payload|null>(null),nav=useNavigate(),[p,setP]=useSearchParams();
 useEffect(()=>{fetch(`${import.meta.env.BASE_URL}data/expectativas-banxico.json`).then(r=>r.json()).then(setData)},[]);
 if(!data)return <Box className="loading">Cargando expectativas de especialistas…</Box>;
 const tab=Math.min(4,Math.max(0,Number(p.get("tab")||0)));
 const setMany=(values:Record<string,string|number>)=>{const n=new URLSearchParams(p);Object.entries(values).forEach(([k,v])=>n.set(k,String(v)));setP(n)};
 const set=(k:string,v:string|number)=>setMany({[k]:v});
 return <Box><AppBar position="sticky" color="transparent" elevation={0}><Toolbar><IconButton onClick={()=>nav("/")}><HomeIcon/></IconButton><Box sx={{flexGrow:1}}><img className="brand-logo header-logo" src={`${import.meta.env.BASE_URL}logo.png`}/></Box><Typography>Encuesta de expectativas</Typography></Toolbar></AppBar><Tabs value={tab} onChange={(_,v)=>set("tab",v)} variant="scrollable" className="tabs"><Tab label="Pronósticos"/><Tab label="Evolución y errores"/><Tab label="Percepción"/><Tab label="Factores y competencia"/><Tab label="Metodología"/></Tabs><Container maxWidth={false} sx={{py:3,px:{xs:1.5,md:3}}}>{tab===0&&<ForecastDashboard data={data} params={p} setMany={setMany}/>} {tab===1&&<HistoricalView data={data} params={p} setMany={setMany}/>} {tab===2&&<OpinionView data={data} params={p} set={set}/>} {tab===3&&<FactorsView data={data} params={p} set={set}/>} {tab===4&&<Methodology data={data}/>}</Container></Box>;
}

function ForecastDashboard({data,params,setMany}:{data:Payload;params:URLSearchParams;setMany:(v:Record<string,string|number>)=>void}){
 const rows=useMemo(()=>objects(data.forecastColumns,data.forecasts),[data]);
 const requestedGroup=params.get("group"),groupKey=(requestedGroup&&requestedGroup in groups?requestedGroup:"rates") as keyof typeof groups,group=groups[groupKey];
 const surveys=[...new Set(rows.filter(r=>group.indicators.includes(String(r.indicator_id) as never)).map(r=>String(r.survey_date)))].sort();
 const survey=params.get("survey")&&surveys.includes(params.get("survey")!)?params.get("survey")!:surveys.at(-1)!;
 const requestedVars=params.get("variables")?.split(",").filter(x=>group.indicators.includes(x as never));
 const activeVars=requestedVars?.length?requestedVars:[...group.indicators];
 const requestedStats=params.get("stats")?.split(",").filter(x=>x in statLabels);
 const activeStats=requestedStats?.length?requestedStats:["median"];
 const toggle=(key:"variables"|"stats",value:string,current:string[])=>{const next=current.includes(value)?current.filter(x=>x!==value):[...current,value];if(next.length)setMany({[key]:next.join(",")})};
 const selectGroup=(next:string)=>{const g=groups[next as keyof typeof groups];setMany({group:next,variables:g.indicators.join(","),stats:"median"})};
 const selected=rows.filter(r=>r.survey_date===survey&&activeVars.includes(String(r.indicator_id)));
 return <Stack spacing={3}><Box><Typography variant="overline" color="primary">CONSENSO DE ESPECIALISTAS</Typography><Typography variant="h3">Pronósticos por grupo de variables</Typography></Box><Tabs value={groupKey} onChange={(_,v)=>selectGroup(v)} className="expectations-subtabs"><Tab value="rates" label="Tasas"/><Tab value="inflation" label="Inflación"/><Tab value="gdp" label="PIB"/></Tabs><Paper className="forecast-controls"><Picker label="Encuesta" value={survey} items={surveys} onChange={v=>setMany({survey:v})}/><ChoiceGroup title="Variables" items={group.indicators} selected={activeVars} labels={labels} onToggle={v=>toggle("variables",v,activeVars)}/><ChoiceGroup title="Estadísticos" items={Object.keys(statLabels)} selected={activeStats} labels={statLabels} onToggle={v=>toggle("stats",v,activeStats)}/></Paper>{groupKey==="gdp"?<><ForecastBlock title="PIB anual" rows={selected.filter(r=>r.forecast_type==="Cierre anual")} indicators={activeVars} stats={activeStats} onOpen={r=>setMany({tab:1,indicator:String(r.indicator_id),period:String(r.period_id)})}/><ForecastBlock title="PIB trimestral" rows={selected.filter(r=>r.forecast_type==="Cierre trimestral")} indicators={activeVars} stats={activeStats} onOpen={r=>setMany({tab:1,indicator:String(r.indicator_id),period:String(r.period_id)})}/></>:<ForecastBlock title={group.label} rows={selected} indicators={activeVars} stats={activeStats} onOpen={r=>setMany({tab:1,indicator:String(r.indicator_id),period:String(r.period_id)})}/>}</Stack>;
}

function ForecastBlock({title,rows,indicators,stats,onOpen}:{title:string;rows:Row[];indicators:string[];stats:string[];onOpen:(r:Row)=>void}){
 const targets=[...new Set(rows.map(r=>String(r.target_period)))];
 const chart=targets.map(target=>({x:target,...Object.fromEntries(indicators.flatMap(ind=>stats.map(stat=>{const r=rows.find(x=>x.target_period===target&&x.indicator_id===ind);return [`${labels[ind]} · ${statLabels[stat]}`,r?.[stat]]})))}));
 const series=indicators.flatMap(ind=>stats.map(stat=>`${labels[ind]} · ${statLabels[stat]}`));
 return <Stack spacing={2}><Typography variant="h5">{title}</Typography>{rows.length?<><Chart data={chart} series={series}/><ForecastTable rows={rows} onOpen={onOpen}/></>:<Paper sx={{p:3}}><Typography color="text.secondary">No hay observaciones para esta selección.</Typography></Paper>}</Stack>;
}

function HistoricalView({data,params,setMany}:{data:Payload;params:URLSearchParams;setMany:(v:Record<string,string|number>)=>void}){
 const rows=useMemo(()=>objects(data.forecastColumns,data.forecasts),[data]),indicators=["FONDEO","CETE28","OTHER","INF_GEN","INF_SUB","GDP_REAL"];
 const indicator=params.get("indicator")&&indicators.includes(params.get("indicator")!)?params.get("indicator")!:"INF_GEN",filtered=rows.filter(r=>r.indicator_id===indicator);
 const periods=[...new Set(filtered.map(r=>String(r.period_id)))].sort(),period=params.get("period")&&periods.includes(params.get("period")!)?params.get("period")!:periods.at(-1)!;
 const shown=filtered.filter(r=>r.period_id===period).sort((a,b)=>String(a.survey_date).localeCompare(String(b.survey_date))),chart=shown.map(r=>({x:r.survey_date,Mediana:r.median,Q1:r.q1,Q3:r.q3,Realizado:r.actual_value})),latest=shown.at(-1);
 return <Stack spacing={3}><Box><Typography variant="overline" color="primary">EVOLUCIÓN DEL PRONÓSTICO</Typography><Typography variant="h3">{labels[indicator]} · {shown[0]?.target_period??period}</Typography></Box><Paper className="forecast-controls"><Picker label="Indicador" value={indicator} items={indicators} display={labels} onChange={v=>setMany({indicator:v})}/><Picker label="Periodo objetivo" value={period} items={periods} onChange={v=>setMany({period:v})}/></Paper>{latest&&<Box className="decision-metrics"><Metric label="Mediana" value={fmt(latest.median)}/><Metric label="Rango intercuartílico" value={fmt(latest.IQR)}/><Metric label="Respuestas" value={String(latest.n_responses??"—")}/><Metric label="Revisión mensual" value={fmt(latest.Revision_1M)}/><Metric label="Dato realizado" value={fmt(latest.actual_value)}/><Metric label="Error" value={fmt(latest.forecast_error)}/></Box>}<Chart data={chart} series={["Mediana","Q1","Q3","Realizado"]}/><ForecastTable rows={shown}/></Stack>;
}

function ChoiceGroup({title,items,selected,labels:display,onToggle}:{title:string;items:readonly string[];selected:string[];labels:Record<string,string>;onToggle:(v:string)=>void}){return <Box><Typography variant="caption" color="text.secondary">{title}</Typography><Stack direction="row" flexWrap="wrap">{items.map(item=><FormControlLabel key={item} control={<Checkbox size="small" checked={selected.includes(item)} onChange={()=>onToggle(item)}/>} label={display[item]}/>)}</Stack></Box>}
function Chart({data,series}:{data:Row[];series:string[]}){return <Paper sx={{p:2}}><ResponsiveContainer width="100%" height={440}><LineChart data={data}><CartesianGrid stroke="#282828"/><XAxis dataKey="x" minTickGap={35}/><YAxis/><Tooltip contentStyle={{background:"#111",border:"1px solid #555"}}/><Legend/>{series.map((s,i)=><Line key={s} dataKey={s} name={s} stroke={colors[i%colors.length]} strokeWidth={2} dot={false} connectNulls/>)}</LineChart></ResponsiveContainer></Paper>}
function ForecastTable({rows,onOpen}:{rows:Row[];onOpen?:(r:Row)=>void}){return <TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>Variable</TableCell><TableCell>Objetivo</TableCell><TableCell align="right">Media</TableCell><TableCell align="right">Mediana</TableCell><TableCell align="right">Q1</TableCell><TableCell align="right">Q3</TableCell><TableCell align="right">Mín.</TableCell><TableCell align="right">Máx.</TableCell><TableCell align="right">n</TableCell><TableCell align="right">Realizado</TableCell><TableCell align="right">Error</TableCell></TableRow></TableHead><TableBody>{rows.map((r,i)=><TableRow hover key={`${r.survey_date}-${r.indicator_id}-${r.period_id}-${i}`} onClick={()=>onOpen?.(r)} sx={{cursor:onOpen?"pointer":"default"}}><TableCell>{labels[String(r.indicator_id)]}</TableCell><TableCell><Chip size="small" label={String(r.target_period)}/></TableCell>{["mean","median","q1","q3","min","max","n_responses","actual_value","forecast_error"].map(k=><TableCell key={k} align="right">{k==="n_responses"?String(r[k]??"—"):fmt(r[k])}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer>}
function Picker({label,value,items,onChange,display={}}:{label:string;value:string;items:string[];onChange:(v:string)=>void;display?:Record<string,string>}){return <FormControl size="small" sx={{minWidth:230}}><InputLabel>{label}</InputLabel><Select label={label} value={value} onChange={e=>onChange(e.target.value)}>{items.map(x=><MenuItem value={x} key={x}>{display[x]??x}</MenuItem>)}</Select></FormControl>}
function Metric({label,value}:{label:string;value:string}){return <Paper className="decision-metric"><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6">{value}</Typography></Paper>}

function OpinionView({data,params,set}:{data:Payload;params:URLSearchParams;set:(k:string,v:string)=>void}){const rows=useMemo(()=>objects(data.opinionColumns,data.opinions),[data]),filtered=rows.filter(r=>r.indicator_id==="OP_ENV"&&r.target_period!=="Número de respuestas"),questions=[...new Set(filtered.map(r=>String(r.forecast_type)))],question=params.get("question")&&questions.includes(params.get("question")!)?params.get("question")!:questions[0],selected=filtered.filter(r=>r.forecast_type===question),series=[...new Set(selected.map(r=>String(r.target_period)))],dates=[...new Set(selected.map(r=>String(r.survey_date)))].sort(),chart=dates.map(d=>({x:d,...Object.fromEntries(series.map(s=>[s,selected.find(r=>r.survey_date===d&&r.target_period===s)?.mean]))}));return <Stack spacing={3}><Box><Typography variant="overline" color="primary">OPINIÓN Y ENTORNO</Typography><Typography variant="h3">Percepción del entorno</Typography></Box><Paper className="forecast-controls"><Picker label="Pregunta" value={question} items={questions} onChange={v=>set("question",v)}/></Paper><Chart data={chart} series={series.slice(0,12)}/></Stack>}
function FactorsView({data,params,set}:{data:Payload;params:URLSearchParams;set:(k:string,v:string)=>void}){const rows=useMemo(()=>objects(data.opinionColumns,data.opinions),[data]),blocks=["OP_FACTORS","OP_COMP"],indicator=params.get("opinion")&&blocks.includes(params.get("opinion")!)?params.get("opinion")!:"OP_FACTORS",filtered=rows.filter(r=>r.indicator_id===indicator),types=[...new Set(filtered.map(r=>String(r.forecast_type)))],type=params.get("factorType")&&types.includes(params.get("factorType")!)?params.get("factorType")!:types[0],selected=filtered.filter(r=>r.forecast_type===type),latest=selected.map(r=>String(r.survey_date)).sort().at(-1)!,ranking=selected.filter(r=>r.survey_date===latest).sort((a,b)=>Number(b.mean??-Infinity)-Number(a.mean??-Infinity)).slice(0,15),dates=[...new Set(selected.map(r=>String(r.survey_date)))].sort().slice(-18),names=ranking.slice(0,8).map(r=>String(r.target_period));return <Stack spacing={3}><Box><Typography variant="overline" color="primary">RIESGOS Y ESTRUCTURA</Typography><Typography variant="h3">{labels[indicator]}</Typography></Box><Paper className="forecast-controls"><Picker label="Bloque" value={indicator} items={blocks} display={labels} onChange={v=>set("opinion",v)}/><Picker label="Medición" value={type} items={types} onChange={v=>set("factorType",v)}/></Paper><Typography variant="h5">Ranking más reciente · {latest}</Typography><TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>Factor o sector</TableCell><TableCell align="right">Valor</TableCell></TableRow></TableHead><TableBody>{ranking.map(r=><TableRow key={String(r.target_period)}><TableCell>{String(r.target_period)}</TableCell><TableCell align="right">{fmt(r.mean)}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Typography variant="h5">Mapa de calor · últimos 18 levantamientos</Typography><Paper sx={{p:2,overflowX:"auto"}}><Box sx={{display:"grid",gridTemplateColumns:`minmax(260px,1fr) repeat(${dates.length},34px)`,gap:"2px",minWidth:900}}>{names.map(name=><Box key={name} sx={{display:"contents"}}><Typography variant="caption" sx={{pr:1}}>{name}</Typography>{dates.map(date=>{const value=Number(selected.find(r=>r.survey_date===date&&r.target_period===name)?.mean??0),alpha=Math.min(.95,.12+Math.abs(value)/Math.max(1,...selected.map(r=>Math.abs(Number(r.mean??0)))));return <Box key={`${name}-${date}`} title={`${date}: ${fmt(value)}`} sx={{height:25,bgcolor:`rgba(242,140,40,${alpha})`}}/>})}</Box>)}</Box></Paper></Stack>}
function Methodology({data}:{data:Payload}){return <Stack spacing={2}><Typography variant="overline" color="primary">FUENTE Y CONSTRUCCIÓN</Typography><Typography variant="h3">Metodología</Typography><Paper sx={{p:3}}><Typography>Fuente: Encuesta sobre las Expectativas de los Especialistas en Economía del Sector Privado, Banco de México.</Typography><Typography color="text.secondary" sx={{mt:1}}>Cobertura: {data.metadata.coverage.from} a {data.metadata.coverage.to}. Los archivos Excel permanecen como fuente de verdad y el sitio consume una extracción JSON validada.</Typography></Paper></Stack>}
