import { useEffect, useState } from "react";
import { AppBar, Box, Button, Checkbox, Chip, Container, FormControl, FormControlLabel, IconButton, InputLabel, MenuItem, Paper, Select, Stack, Tab, Tabs, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Toolbar, Tooltip, Typography } from "@mui/material";
import { Download, Home as HomeIcon, InfoOutlined } from "@mui/icons-material";
import { CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { useNavigate, useSearchParams } from "react-router-dom";
import { EnhancedBiasTab, EnhancedCohortTab, ForecastMethodology } from "./forecast-analysis";
import { calculateAxisScale } from "./chart-scale";

type Category={code:string;label:string;color:string}; type Decision={id:string;date:string;status:string;hasForecasts:boolean;source:string};
type Forecast={id:string;decisionId:string;date:string;category:string;period:string;value:number;source:string};
type Data={metadata:{generatedAt:string;source:string;biasDefinition:string;lastObservedPeriod:string};config:{categories:Category[];horizons:number[];cohorts:{id:string;label:string;min:number;max:number|null;color:string}[]};decisions:Decision[];forecasts:Forecast[];observed:Record<string,Record<string,number|null>>;decisionCrosswalk:{forecastDecisionId:string;decisionExplorerId:string;date:string}[]};
const fmt=(v:number|null|undefined)=>v==null?"—":`${v.toFixed(2)}%`; const dateFmt=(s:string)=>new Date(`${s}T00:00:00`).toLocaleDateString("es-MX",{day:"numeric",month:"short",year:"numeric"});
const quarterEnd=(p:string)=>{const [y,q]=p.split("-T").map(Number);return new Date(Date.UTC(y,q*3,0)).toISOString().slice(0,10)};
const help:Record<string,string>={D0:"Última decisión antes del cierre del trimestre.","D-n":"Número de decisiones efectivas anteriores a D0.","D+n":"Publicaciones posteriores al cierre.",observado:"Resultado usado por el estudio cuando el periodo concluyó.",definitivo:"Dato revisado o definitivo cuando difiere del observado."};
function Help({term}:{term:string}){return <Tooltip title={help[term]??term}><InfoOutlined fontSize="inherit" sx={{ml:.5,verticalAlign:"middle"}}/></Tooltip>}
function useData(){const [data,setData]=useState<Data|null>(null);useEffect(()=>{fetch(`${import.meta.env.BASE_URL}data/pronosticos-banxico.json`).then(r=>r.json()).then(setData)},[]);return data}

export default function ForecastsRadar(){const data=useData();const nav=useNavigate();const [params,setParams]=useSearchParams();const tab=Math.min(5,Math.max(0,Number(params.get("tab")??0)));if(!data)return <Box className="loading">Cargando Pronósticos de Banxico…</Box>;
 const effective=data.decisions.filter(d=>d.status==="Efectiva"&&d.hasForecasts).sort((a,b)=>b.date.localeCompare(a.date)); const periods=[...new Set(data.forecasts.map(f=>f.period))].sort();
 const decision=params.get("decision")&&effective.some(d=>d.id===params.get("decision"))?params.get("decision")!:effective[0].id; const period=params.get("period")&&periods.includes(params.get("period")!)?params.get("period")!:periods.at(-1)!;
 const category=params.get("category")&&data.config.categories.some(c=>c.code===params.get("category"))?params.get("category")!:"INPC"; const visible=(params.get("visible")?.split(",").filter(x=>data.config.categories.some(c=>c.code===x))??data.config.categories.map(c=>c.code));
 const compared=(params.get("compare")?.split(",").filter(x=>periods.includes(x))??defaultCompare(periods,data));
 const set=(values:Record<string,string|number>)=>{const n=new URLSearchParams(params);Object.entries(values).forEach(([k,v])=>n.set(k,String(v)));setParams(n)};
 return <Box className="forecasts-module"><AppBar position="sticky" color="transparent" elevation={0}><Toolbar><IconButton onClick={()=>nav("/")}><HomeIcon/></IconButton><Box sx={{flexGrow:1}}><img className="brand-logo header-logo" src={`${import.meta.env.BASE_URL}logo.png`}/></Box><Typography className="forecast-title">Pronósticos de Banxico</Typography><Button startIcon={<Download/>} onClick={()=>window.print()}>Exportar esta vista a PDF</Button></Toolbar></AppBar>
 <Tabs value={tab} onChange={(_,v)=>set({tab:v})} variant="scrollable" className="tabs"><Tab label="Pronósticos por decisión"/><Tab label="Evolución de un periodo"/><Tab label="Comparación de periodos"/><Tab label="Subestimación histórica"/><Tab label="Subestimación según inflación observada"/><Tab label="Conclusiones y metodología"/></Tabs>
 <Container maxWidth={false} sx={{py:3,px:{xs:1.5,md:3}}} className="forecast-print-area"><Box className="print-header"><Typography variant="h4">Pronósticos de Banxico</Typography><Typography>{new Date().toLocaleDateString("es-MX")} · Fuente: {data.metadata.source}</Typography></Box>
 {tab===0&&<DecisionTab data={data} decision={decision} visible={visible} set={set} nav={nav}/>} {tab===1&&<PeriodTab data={data} period={period} visible={visible} set={set}/>} {tab===2&&<CompareTab data={data} compared={compared} category={category} set={set}/>} {tab===3&&<EnhancedBiasTab data={data} category={category} set={set}/>} {tab===4&&<EnhancedCohortTab data={data} category={category} set={set}/>} {tab===5&&<ForecastMethodology/>}</Container></Box>}
const defaultCompare=(periods:string[],data:Data)=>{const observed=periods.filter(p=>data.observed[p]?.INPC!=null&&p<=data.metadata.lastObservedPeriod).at(-1);const open=periods.find(p=>p>data.metadata.lastObservedPeriod);return [observed,open].filter(Boolean) as string[]};
function CategoryChecks({data,visible,set}:{data:Data;visible:string[];set:(x:Record<string,string>)=>void}){return <Stack direction="row" flexWrap="wrap">{data.config.categories.map(c=><FormControlLabel key={c.code} control={<Checkbox checked={visible.includes(c.code)} sx={{color:c.color,"&.Mui-checked":{color:c.color}}} onChange={()=>set({visible:(visible.includes(c.code)?visible.filter(x=>x!==c.code):[...visible,c.code]).join(",")})}/>} label={c.label}/>)}</Stack>}
function Selector({label,value,items,onChange}:{label:string;value:string;items:string[];onChange:(v:string)=>void}){return <FormControl size="small" sx={{minWidth:240}}><InputLabel>{label}</InputLabel><Select label={label} value={value} onChange={e=>onChange(e.target.value)}>{items.map(x=><MenuItem value={x} key={x}>{x.startsWith("DPM-")?dateFmt(x.slice(4)):x}</MenuItem>)}</Select></FormControl>}
function Panel({title,question,children}:{title:string;question:string;children:React.ReactNode}){return <Stack spacing={2.5}><Box><Typography variant="overline" color="primary">{question}</Typography><Typography variant="h3">{title}</Typography></Box>{children}</Stack>}
function DecisionTab({data,decision,visible,set,nav}:{data:Data;decision:string;visible:string[];set:(x:Record<string,string|number>)=>void;nav:(x:string)=>void}){const decisions=data.decisions.filter(d=>d.status==="Efectiva"&&d.hasForecasts).sort((a,b)=>b.date.localeCompare(a.date));const rows=data.forecasts.filter(f=>f.decisionId===decision);const periods=[...new Set(rows.map(x=>x.period))].sort();const chart=periods.map(period=>({period,...Object.fromEntries(rows.filter(x=>x.period===period).map(x=>[x.category,x.value]))}));const cross=data.decisionCrosswalk.find(x=>x.forecastDecisionId===decision);return <Panel title="Trayectoria publicada" question="¿Qué trayectoria de inflación publicó Banxico en esta decisión monetaria?"><Paper className="forecast-controls"><Selector label="Decisión efectiva" value={decision} items={decisions.map(x=>x.id)} onChange={v=>set({decision:v})}/><CategoryChecks data={data} visible={visible} set={set}/><Button disabled={!cross} onClick={()=>nav(`/decisiones?decision=${cross?.decisionExplorerId}`)}>Ver decisión monetaria</Button></Paper><ForecastChart data={chart} categories={data.config.categories.filter(c=>visible.includes(c.code))} x="period"/><DataTable periods={periods} rows={rows} data={data} actions={p=><><Button size="small" onClick={()=>set({tab:1,period:p})}>Ver evolución</Button><Button size="small" onClick={()=>set({tab:2,compare:p,category:"INPC"})}>Agregar al comparador</Button></>}/></Panel>}
function PeriodTab({data,period,visible,set}:{data:Data;period:string;visible:string[];set:(x:Record<string,string|number>)=>void}){const periods=[...new Set(data.forecasts.map(f=>f.period))].sort();const rows=data.forecasts.filter(f=>f.period===period).sort((a,b)=>a.date.localeCompare(b.date));const dates=[...new Set(rows.map(x=>x.date))];const chart=dates.map(date=>({date,...Object.fromEntries(rows.filter(x=>x.date===date).map(x=>[x.category,x.value]))}));return <Panel title={`Evolución de ${period}`} question="¿Cómo fue cambiando el pronóstico de Banxico para un trimestre determinado?"><Paper className="forecast-controls"><Selector label="Periodo pronosticado" value={period} items={periods} onChange={v=>set({period:v})}/><CategoryChecks data={data} visible={visible} set={set}/><Button onClick={()=>set({tab:2,compare:period})}>Agregar al comparador</Button></Paper><ForecastChart data={chart} categories={data.config.categories.filter(c=>visible.includes(c.code))} x="date" observed={data.observed[period]}/><TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>Decisión</TableCell>{data.config.categories.map(c=><TableCell key={c.code}>{c.label}</TableCell>)}<TableCell>Acción</TableCell></TableRow></TableHead><TableBody>{dates.map(d=><TableRow key={d}><TableCell>{dateFmt(d)}</TableCell>{data.config.categories.map(c=>{const current=rows.find(x=>x.date===d&&x.category===c.code);const prior=rows.filter(x=>x.category===c.code&&x.date<d).at(-1);return <TableCell key={c.code}>{fmt(current?.value)}{current&&prior?<small> ({(current.value-prior.value).toFixed(2)})</small>:null}</TableCell>})}<TableCell><Button onClick={()=>set({tab:0,decision:rows.find(x=>x.date===d)!.decisionId})}>Ver decisión</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></Panel>}
function relative(data:Data,period:string,category:string){const close=quarterEnd(period);const effective=data.decisions.filter(d=>d.status==="Efectiva").sort((a,b)=>a.date.localeCompare(b.date));const d0=effective.filter(d=>d.date<=close).at(-1);if(!d0)return[];const i0=effective.findIndex(d=>d.id===d0.id);return data.forecasts.filter(f=>f.period===period&&f.category===category).map(f=>{const i=effective.findIndex(d=>d.id===f.decisionId);return {...f,relative:i-i0,label:`D${i-i0>=0?"+":""}${i-i0}`}}).sort((a,b)=>a.relative-b.relative)}
function comparisonCalendar(data:Data){const priority:Record<string,number>={Efectiva:3,Programada:2,Estimada:1};const byDate=new Map<string,Decision>();data.decisions.forEach(decision=>{const current=byDate.get(decision.date);if(!current||(priority[decision.status]??0)>(priority[current.status]??0))byDate.set(decision.date,decision)});return [...byDate.values()].sort((a,b)=>a.date.localeCompare(b.date))}
function comparisonRelative(data:Data,period:string,category:string){const calendar=comparisonCalendar(data);const close=quarterEnd(period);let d0Index=-1;calendar.forEach((decision,index)=>{if(decision.date<=close)d0Index=index});if(d0Index<0)return[];return data.forecasts.filter(f=>f.period===period&&f.category===category).map(f=>{const index=calendar.findIndex(d=>d.id===f.decisionId||d.date===f.date);return {...f,relative:index-d0Index}}).filter(f=>f.relative>=-calendar.length).sort((a,b)=>a.relative-b.relative)}
function comparisonPositions(data:Data,period:string,category:string){const rows=comparisonRelative(data,period,category);if(!rows.length)return[0];const minimum=Math.min(0,...rows.map(row=>row.relative));const maximum=Math.max(0,...rows.map(row=>row.relative));return Array.from({length:maximum-minimum+1},(_,index)=>minimum+index)}
function CompareTab({data,compared,category,set}:{data:Data;compared:string[];category:string;set:(x:Record<string,string>)=>void}){const periods=[...new Set(data.forecasts.map(f=>f.period))].sort();const points=[...new Set(compared.flatMap(p=>comparisonPositions(data,p,category)))].sort((a,b)=>a-b);const rows=Object.fromEntries(compared.map(p=>[p,comparisonRelative(data,p,category)]));const chart=points.map(rel=>({relative:rel,label:rel===0?"D0":`D${rel>0?"+":""}${rel}`,...Object.fromEntries(compared.map(p=>[p,rows[p].find(x=>x.relative===rel)?.value]))}));return <Panel title="Comparación en tiempo relativo" question="¿Cómo evolucionan distintos pronósticos al acercarse al resultado observado?"><Paper className="forecast-controls"><Selector label="Categoría" value={category} items={data.config.categories.map(c=>c.code)} onChange={v=>set({category:v})}/><Selector label="Agregar periodo" value={periods.find(p=>!compared.includes(p))??periods[0]} items={periods.filter(p=>!compared.includes(p))} onChange={v=>set({compare:[...compared,v].join(",")})}/><Stack direction="row">{compared.map(p=><Chip key={p} label={p} onDelete={()=>set({compare:compared.filter(x=>x!==p).join(",")})}/>)}</Stack></Paper><RelativeComparisonChart chart={chart} periods={compared} colors={data.config.categories.map(c=>c.color)}/><Typography color="text.secondary">D0 <Help term="D0"/> · Las decisiones programadas y estimadas cuentan como posiciones del calendario, pero solo las decisiones efectivas pueden mostrar un valor publicado.</Typography></Panel>}
function RelativeComparisonChart({chart,periods,colors}:{chart:Record<string,unknown>[];periods:string[];colors:string[]}){const values=chart.flatMap(row=>periods.map(period=>row[period])).filter((value):value is number=>typeof value==="number"&&Number.isFinite(value));const scale=calculateAxisScale(values,2);return <ResponsiveContainer width="100%" height={420}><LineChart data={chart}><CartesianGrid stroke="#282828"/><XAxis dataKey="label"/><YAxis domain={scale.domain} ticks={scale.ticks} allowDataOverflow/><ReferenceLine x="D0" stroke="#fff" label="D0"/><ChartTooltip/><Legend verticalAlign="top" align="center" height={38}/>{periods.map((period,index)=><Line key={period} connectNulls={false} dataKey={period} name={period} stroke={colors[index%colors.length]}/>)}</LineChart></ResponsiveContainer>}
function metrics(data:Data,category:string,cohort?:{min:number;max:number|null}){const all=[...new Set(data.forecasts.map(f=>f.period))].flatMap(p=>{const o=data.observed[p]?.[category];if(o==null||cohort&&(o<=cohort.min||cohort.max!=null&&o>cohort.max))return[];return relative(data,p,category).map(x=>({...x,error:x.value-o,observed:o,period:p}))});return data.config.horizons.map(h=>{const a=all.filter(x=>x.relative===h),n=a.length,mean=(key:"value"|"observed"|"error")=>n?a.reduce((s,x)=>s+x[key],0)/n:null;const mae=n?a.reduce((s,x)=>s+Math.abs(x.error),0)/n:null,rmse=n?Math.sqrt(a.reduce((s,x)=>s+x.error*x.error,0)/n):null;return {h,label:`D${h}`,n,forecast:mean("value"),observed:mean("observed"),bias:mean("error"),mae,rmse}})}
function MetricTable({rows}:{rows:ReturnType<typeof metrics>}){return <TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>Horizonte</TableCell><TableCell>n</TableCell><TableCell>Pronóstico</TableCell><TableCell>Observado</TableCell><TableCell>Sesgo</TableCell><TableCell>MAE</TableCell><TableCell>RMSE</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.h}><TableCell>{r.label}</TableCell><TableCell>{r.n}</TableCell><TableCell>{fmt(r.forecast)}</TableCell><TableCell>{fmt(r.observed)}</TableCell><TableCell>{fmt(r.bias)}</TableCell><TableCell>{fmt(r.mae)}</TableCell><TableCell>{fmt(r.rmse)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}
function BiasTab({data,category,set}:{data:Data;category:string;set:(x:Record<string,string>)=>void}){const rows=metrics(data,category);return <Panel title="Sesgo histórico" question="¿Banxico suele sobreestimar o subestimar la inflación?"><Paper className="forecast-controls"><Selector label="Categoría" value={category} items={data.config.categories.map(c=>c.code)} onChange={v=>set({category:v})}/><Typography><b>Sesgo = Pronóstico − Observado.</b> Negativo: subestimación; positivo: sobreestimación.</Typography></Paper><ForecastChart data={rows} categories={[{code:"forecast",label:"Pronóstico promedio",color:"#f28c28"},{code:"observed",label:"Observado promedio",color:"#e8e8e8"},{code:"bias",label:"Sesgo promedio",color:"#4da3ff"}]} x="label"/><MetricTable rows={rows}/></Panel>}
function CohortTab({data,category,set}:{data:Data;category:string;set:(x:Record<string,string>)=>void}){return <Panel title="Sesgo según inflación observada" question="¿Cómo cambia el desempeño según el nivel que finalmente alcanzó la inflación?"><Paper className="forecast-controls"><Selector label="Categoría" value={category} items={data.config.categories.map(c=>c.code)} onChange={v=>set({category:v})}/></Paper>{data.config.cohorts.map(c=><Box key={c.id}><Typography variant="h5" sx={{mb:1}}>{c.label}</Typography><MetricTable rows={metrics(data,category,c)}/></Box>)}<Paper sx={{p:2}}><Typography color="text.secondary">Cohortes determinadas ex post; análisis descriptivo, no causal. Los pronósticos de un mismo periodo están correlacionados y el número efectivo de experiencias independientes se aproxima al número de periodos. Las muestras de horizontes largos pueden ser menores.</Typography></Paper></Panel>}
function ForecastChart({data,categories,x,observed}:{data:Record<string,unknown>[];categories:Category[];x:string;observed?:Record<string,number|null>}){const values=data.flatMap(row=>categories.map(category=>row[category.code])).filter((value):value is number=>typeof value==="number"&&Number.isFinite(value));const scale=calculateAxisScale(values,3);return <Paper sx={{p:2}}><ResponsiveContainer width="100%" height={420}><LineChart data={data}><CartesianGrid stroke="#282828"/><XAxis dataKey={x}/><YAxis domain={scale.domain} ticks={scale.ticks} allowDataOverflow/><ChartTooltip contentStyle={{background:"#111",border:"1px solid #555"}}/><Legend verticalAlign="top" align="center" height={38}/>{categories.map(c=><Line connectNulls={false} key={c.code} dataKey={c.code} name={c.label} stroke={c.color} strokeWidth={2}/>)}</LineChart></ResponsiveContainer>{observed&&<Typography color="text.secondary">Dato observado <Help term="observado"/>: {categories.map(c=>`${c.label} ${fmt(observed[c.code])}`).join(" · ")}</Typography>}</Paper>}
function DataTable({periods,rows,data,actions}:{periods:string[];rows:Forecast[];data:Data;actions:(p:string)=>React.ReactNode}){return <TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>Periodo</TableCell>{data.config.categories.map(c=><TableCell key={c.code}>{c.label}</TableCell>)}<TableCell>Observado</TableCell><TableCell>Acciones</TableCell></TableRow></TableHead><TableBody>{periods.map(p=><TableRow key={p}><TableCell>{p}</TableCell>{data.config.categories.map(c=><TableCell key={c.code}>{fmt(rows.find(x=>x.period===p&&x.category===c.code)?.value)}</TableCell>)}<TableCell>{fmt(data.observed[p]?.INPC)}</TableCell><TableCell>{actions(p)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}

void BiasTab;
void CohortTab;

